package dao;

import dao.mappers.ResultSetMapper;
import domain.Book;

import java.sql.Connection;
import java.sql.SQLException;

/**
 * Created by Michal on 08.01.2018.
 */
public class BookRepository extends RepositoryBase<Book> {
    private static final String TABLE_NAME = "books";

    public BookRepository(Connection connection, ResultSetMapper<Book> mapper) throws SQLException {
        super(connection, mapper);
    }

    protected void setupUpdate(Book book) throws SQLException {

    }

    protected void setupInsert(Book person) throws SQLException {

    }

    @Override
    protected String tableName() {
        return TABLE_NAME;
    }

    @Override
    protected String createTableSql() {
        return "CREATE TABLE " + tableName() + "(" +
                "id INT GENERATED BY DEFAULT AS IDENTITY, " +
                "author_first_name VARCHAR(50), " +
                "author_last_name VARCHAR(50), " +
                "ISBN VARCHAR(50), " +
                "title VARCHAR(50), " + ")" ;
    }

    @Override
    protected String updateSql() {
        return "UPDATE " + tableName() + "SET (author_first_name, author_last_name, ISBN, title) = (?, ?, ?, ?)" +
                " WHERE id = ?";
    }

    @Override
    protected String insertSql() {
        return "INSERT INTO " + tableName() + "(author_first_name, author_last_name, ISBN, title) VALUES(?, ?, ?, ?)";
    }
}
