package dao;

import dao.mappers.ResultSetMapper;
import domain.Library;

import java.sql.Connection;
import java.sql.SQLException;

/**
 * Created by Michal on 08.01.2018.
 */
public class LibraryRepository extends RepositoryBase<Library> {
    private static final String TABLE_NAME = "libraries";


    public LibraryRepository(Connection connection, ResultSetMapper<Library> mapper) throws SQLException {
        super(connection, mapper);
    }

    protected void setupUpdate(Library library) throws SQLException {

    }

    protected void setupInsert(Library person) throws SQLException {

    }

    protected String tableName() {
        return null;
    }

    protected String createTableSql() {
        return "CREATE TABLE " + tableName() + "(" +
                "id INT GENERATED BY DEFAULT AS IDENTITY, " +
                "name VARCHAR(50), " +
                "type VARCHAR(50)" + ")" ;
    }

    protected String updateSql() {
        return "UPDATE " + tableName() + " SET (name, type) = (?, ?)" +
                " WHERE id = ?";
    }

    protected String insertSql() {
        return "INSERT INTO " + tableName() + "(name, type) VALUES(?, ?)";
    }

}
