package dao;

import dao.mappers.ResultSetMapper;
import dao.mappers.UserResultMapper;
import domain.User;

import java.sql.Connection;
import java.sql.SQLException;

/**
 * Created by Michal on 08.01.2018.
 */
public class UserRepository extends RepositoryBase<User> {
    private static final String TABLE_NAME = "users";

    public UserRepository(Connection connection, ResultSetMapper<User> mapper) throws SQLException {
        super(connection, mapper);
    }

    protected void setupUpdate(User user) throws SQLException {

    }

    protected void setupInsert(User person) throws SQLException {

    }

    protected String tableName() {
        return TABLE_NAME;
    }

    protected String createTableSql() {
        return "CREATE TABLE " + tableName() + "(" +
                "id INT GENERATED BY DEFAULT AS IDENTITY, " +
                "first_name VARCHAR(50), " +
                "last_name VARCHAR(50), " +
                "card VARCHAR(50), " + ")";
    }

    protected String updateSql() {
        return "UPDATE " + tableName() + " SET (first_name, last_name, card) = (?, ?, ?)" +
                " WHERE id = ?";
    }

    protected String insertSql() {
        return "INSERT INTO " + tableName() + "(first_name, last_name, card) VALUES(?, ?, ?)";
    }
}
